"""                 
FIPS codes for counties in the state/territory: Alaska.
"""



Aleutians_East_Borough = '013'
Aleutians_West_Census_Area = '016'
Anchorage_Municipality = '020'
Bethel_Census_Area = '050'
Bristol_Bay_Borough = '060'
Chugach_Census_Area = '063'
Copper_River_Census_Area = '066'
Denali_Borough = '068'
Dillingham_Census_Area = '070'
Fairbanks_North_Star_Borough = '090'
Haines_Borough = '100'
Hoonah_Angoon_Census_Area = '105'
Juneau_City_And_Borough = '110'
Kenai_Peninsula_Borough = '122'
Ketchikan_Gateway_Borough = '130'
Kodiak_Island_Borough = '150'
Kusilvak_Census_Area = '158'
Lake_And_Peninsula_Borough = '164'
Matanuska_Susitna_Borough = '170'
Nome_Census_Area = '180'
North_Slope_Borough = '185'
Northwest_Arctic_Borough = '188'
Petersburg_Borough = '195'
Prince_Of_Wales_Hyder_Census_Area = '198'
Sitka_City_And_Borough = '220'
Skagway_Municipality = '230'
Southeast_Fairbanks_Census_Area = '240'
Wrangell_City_And_Borough = '275'
Yakutat_City_And_Borough = '282'
Yukon_Koyukuk_Census_Area = '290'
