"""                 
FIPS codes for counties in the state/territory: Massachusetts.
"""



BARNSTABLE_COUNTY = '001'
BERKSHIRE_COUNTY = '003'
BRISTOL_COUNTY = '005'
DUKES_COUNTY = '007'
ESSEX_COUNTY = '009'
FRANKLIN_COUNTY = '011'
HAMPDEN_COUNTY = '013'
HAMPSHIRE_COUNTY = '015'
MIDDLESEX_COUNTY = '017'
NANTUCKET_COUNTY = '019'
NORFOLK_COUNTY = '021'
PLYMOUTH_COUNTY = '023'
SUFFOLK_COUNTY = '025'
WORCESTER_COUNTY = '027'
