"""                 
FIPS codes for counties in the state/territory: New Hampshire.
"""



BELKNAP_COUNTY = '001'
CARROLL_COUNTY = '003'
CHESHIRE_COUNTY = '005'
COOS_COUNTY = '007'
GRAFTON_COUNTY = '009'
HILLSBOROUGH_COUNTY = '011'
MERRIMACK_COUNTY = '013'
ROCKINGHAM_COUNTY = '015'
STRAFFORD_COUNTY = '017'
SULLIVAN_COUNTY = '019'
