"""                 
FIPS codes for counties in the state/territory: Vermont.
"""



ADDISON_COUNTY = '001'
BENNINGTON_COUNTY = '003'
CALEDONIA_COUNTY = '005'
CHITTENDEN_COUNTY = '007'
ESSEX_COUNTY = '009'
FRANKLIN_COUNTY = '011'
GRAND_ISLE_COUNTY = '013'
LAMOILLE_COUNTY = '015'
ORANGE_COUNTY = '017'
ORLEANS_COUNTY = '019'
RUTLAND_COUNTY = '021'
WASHINGTON_COUNTY = '023'
WINDHAM_COUNTY = '025'
WINDSOR_COUNTY = '027'
